### ISSUE TITLE
Update Readme: Only works with v4.9.2

### ISSUE THREAD

**Issue by cfryerdev** [tnk4on/podman-machine-rosetta#1]
Note: This only works with v4.9.2. Any version past, this fails with vfkit exiting with code 0 or 2 (depending on if you have the podman log level debug flag on or not)

**Comment by cfryerdev** [comment]
Although, next issue is `cat /proc/sys/fs/binfmt_misc/rosetta` is empty.

**Comment by tnk4on** [comment]
@cfryerdev Fixed and works on v4.9.4.
Please retry it.
